### ISSUE TITLE
Not working after recent plattform change

### ISSUE THREAD

**Issue by MirkoKas** [toto/solarman-widget-scriptable#1]
Since Deye switched their Plattform for international users the script doesn’t work anymore. 

See also https://github.com/raschy/ioBroker.solarmanpv/issues/66

**Comment by toto** [comment]
Basically just the hostname changed to `globalhomeappapi.solarmanpv.com`. Thanks for the heads up. 

This should be fixed as of 05b9e61065e83a43460aed2311be0b95feca3937

**Comment by MirkoKas** [comment]
Thx. I found a different hostname but that didn’t work for me. So I thought it needed some more changes within the script.

**Comment by toto** [comment]
The new code seems to work here: ![image](https://user-images.githubusercontent.com/15453/232826587-cf087594-ffbb-4083-8c0b-e4b4d7030951.png). 

The token also needs refresh but the codes does that on every request anyways.

**Comment by MirkoKas** [comment]
Does work for me too
